### ISSUE TITLE
globalize built-in messages in terminal package

### ISSUE THREAD

**Issue by boyang9527** [IBM-Bluemix/bluemix-cli-sdk#21]

**Comment by eafurlan** [comment]
Was this fixed? I'm still seeing the issue.

**Comment by weieigao** [comment]
We haven't bumped bluemix-cli-sdk with i18n into Bluemix CLI yet.

**Comment by eafurlan** [comment]
I'm afraid I'm still not seeing the translated strings - I see that the code to accommodate translated strings is in place, but is there another issue for the actual translation that I can watch so I know when this is resolved?
