### ISSUE TITLE
bx cf help -a incomplete

### ISSUE THREAD

**Issue by maboud** [IBM-Bluemix/bluemix-cli-sdk#44]
after updating from **bx cli 0.5.4** (_cf 6.18.0_) to **bx cli 0.5.5** (_cf 6.26.0_); bx cf help -a doesn't show the complete list of commands anymore. I tried cf 6.26.0 on a separate machine, and it seems to work just fine, so I guess it might be a bx issue
<img width="676" alt="screen shot 2017-07-05 at 3 06 12 pm" src="https://user-images.githubusercontent.com/25465137/27882018-f63b98b6-6198-11e7-8002-71d53ba68a20.png">

**Comment by weieigao** [comment]
Will fix in next CLI release

**Comment by weieigao** [comment]
@maboud, the bug is fixed in cli 0.5.5
