### ISSUE TITLE
Accessing info from plugin context blows up 

### ISSUE THREAD

**Issue by neelashah** [IBM-Bluemix/bluemix-cli-sdk#49]
I need to access the contextual information for using values in the command help text for substitution values. 
In support for that, need the ability to get the plugin context since its not available in the GetMetadata() flow...Currently, when I try to access anything from the plugin context, the install of my plugin blows up (builds fine) with the following error - 

```Installing binary...
FAILED
Unable to obtain plug-in's metadata. Error: exit status 2```

**Comment by boyang9527** [comment]
per discussion, we will add a method to get the plugin context besides the one that passed into Run() method.

**Comment by neelashah** [comment]
@boyang9527 @weieigao Is this ready for consumption? I am unclear what env this commit is available in. Is it already in prod for us to use?
