### ISSUE TITLE
Windows color support - use of golang.org/x/crypto/ssh/terminal.IsTerminal is not correct for windows

### ISSUE THREAD

**Issue by jchunkins** [IBM-Bluemix/bluemix-cli-sdk#53]
Color support at this line is not correct.
https://github.com/IBM-Bluemix/bluemix-cli-sdk/blob/49eedfb694cfeee351c3bd15b837c69a94587fa3/bluemix/terminal/color.go#L140

Should be
```terminal.IsTerminal(int(os.Stdout.Fd()))```

**Comment by boyang9527** [comment]
@weieigao  pls take care of this.

**Comment by weieigao** [comment]
Should be fixed in 0.6.1
