### ISSUE TITLE
Corporate plugin?

### ISSUE THREAD

**Issue by ericis** [IBM-Bluemix/bluemix-cli-sdk#59]
How would a company make a custom plug-in that is not published to the Bluemix repository? Would you recommend just downloading the plugin files and running install on a local copy? It doesn't appear that I can specify multiple repositories...

**Comment by weieigao** [comment]
You can also install a plugin from a url (for example `bx plugin install http://download.example.com/my-plugin`). 

The company can also have their own plugin repository. Use  `bx plugin repo-add` to add a plugin repo, and use `-r` to specify a repo in `bx plugin install`
