### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by frosenberg** [IBM-Bluemix/bluemix-cli-sdk#6]
```
$ go get github.com/IBM-Bluemix/bluemix-cli-sdk/plugin
# github.com/IBM-Bluemix/bluemix-cli-sdk/bluemix/configuration/core_config
../../../github.com/IBM-Bluemix/bluemix-cli-sdk/bluemix/configuration/core_config/repository.go:50: cannot use NewCFConfigAdapterFromPersistor(cfPersistor, errHandler) (type *cfConfigAdapter) as type CFReadWriter in field value:
	*cfConfigAdapter does not implement CFReadWriter (missing LoggregatorEndpoint method)
```

I run go 1.7.5 on macOS.

**Comment by boyang9527** [comment]
Looks like the dependency the CLI SDK is using mismatch with the one you get.

You may 'go get github.com/IBM-Bluemix/bluemix-cli-sdk'  and restore the dependency using ' govender sync'

**Comment by frosenberg** [comment]
Why do I need govendor sync? I'm an API user and I just doing a `go get`...

**Comment by sreya92** [comment]
This also occurs when trying to use [glide](https://github.com/Masterminds/glide) as a dependency manager. Trying to compile will result in the same error listed in the original comment
