### ISSUE TITLE
Plugin's config data is not dynamically loaded

### ISSUE THREAD

**Issue by neelashah** [IBM-Bluemix/bluemix-cli-sdk#67]
Based on my findings and discussion with Bo Yang, Bluemix is loading the config data for a given plugin at  plugin install time and thereafter only uses those initially loaded values. So there is no opportunity to use/load config values that are dynamic/dependent on where the service itself is running since that data would be available at bx cs init time. 

**Use Case**
Wanda is a Cloud company in China that IBM has signed a contract with to deliver the Cloud solution to for Wanda to sell as its own. There are a specific set of services that are included in the Wanda contract, Container Service being one of them. Hence, we need the ability to `rebrand` our container service. This means we need the ability to replace phrases like `IBM` 'IBM Bluemix`, etc with phrases that are provided by Wanda. The replacement focus is on the areas that are exposed to the end user - one of these areas being the CLI messages, including the --help messages. 
Many other services will also have this need that are included in the Wanda contract. 

**Options I see are as follows -**

1. Provide the ability to update the plugin metadata after its been installed. This might be the most flexible.

2. Allow plugins to specify a config file with the rebranding information for the plugin that is uploaded along with the plugin binary to the bluemix cli repo. This would allow us to provide a config file for IBM if its being uploaded to the `IBM Bluemix repo` or provide a `Wanda` config file if the plugin is being uploaded for the Wanda repo.

**Comment by neelashah** [comment]
@boyang9527 FYI ^ Also, see option 1 above - we did not discuss but wanted you to give it some thought as well....

**Comment by boyang9527** [comment]
we would like to go with option 2 but give an interface for plugin to retrieve the cloud config ... so you don't need to care how and where it is stored.
